Repository jothikaaravindhan/kubernetes-cost-optimization-operator, pull requests merged in 2025-05, with the labels that each got.

#81 Rename custom resource to CostOptimizationRule
  app/build.gradle
  app/crds/costoptimizationoperatorcustomresources.org.jothika.costoperator-v1.yml
  app/crds/costoptimizationoperatorcustomresources.org.jothika.costoperator-v1beta1.yml
  app/crds/costoptimizationrules.org.jothika.costoperator-v1.yml
  app/src/main/java/org/jothika/costoperator/CostOptimizationOperatorStatus.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRule.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleSpec.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleStatus.java
  app/src/main/java/org/jothika/costoperator/Runner.java
Labels: Pull Request

#82 Metrics server availability check before starting the operator
  app/build.gradle
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/Runner.java
  app/src/main/java/org/jothika/costoperator/metrics/MetricsUtils.java
  app/src/test/java/org/jothika/costoperator/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/metrics/MetricsUtilsTest.java
Labels: Pull Request

#83 Build and Push Docker Image to DockerHub Registry
  .github/workflows/docker-publish.yml
Labels: enhancement

#84 Jacoco spotless configuration added
  .github/workflows/gradle.yml
  app/build.gradle
  app/src/main/java/org/jothika/costoperator/CostOptimizationRule.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleSpec.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleStatus.java
  app/src/main/java/org/jothika/costoperator/Runner.java
  app/src/test/java/org/jothika/costoperator/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/metrics/MetricsUtilsTest.java
Labels: enhancement

#88 Reconciliation interval added
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/events/EventGenerator.java
  app/src/main/java/org/jothika/costoperator/events/EventType.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/test/java/org/jothika/costoperator/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/TestMockUtils.java
  app/src/test/java/org/jothika/costoperator/events/EventGeneratorTest.java
  app/src/test/java/org/jothika/costoperator/events/EventTypeTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/metrics/MetricsUtilsTest.java
Labels: Pull Request

#89 Introduce Spring Boot with version 3.4.5
  app/build.gradle
  app/src/main/java/org/jothika/costoperator/BeanConfiguration.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/Runner.java
  app/src/main/java/org/jothika/costoperator/events/EventGenerator.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/main/java/org/jothika/costoperator/metrics/MetricsService.java
  app/src/test/java/org/jothika/costoperator/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/metrics/MetricsServiceTest.java
Labels: Pull Request

#90 Send mail functionality added
  app/build.gradle
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/main/java/org/jothika/costoperator/mail/EmailService.java
  app/src/main/resources/application.properties
  app/src/main/resources/templates/pod-alert.html
  app/src/test/java/org/jothika/costoperator/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/TestMockUtils.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/mail/EmailServiceTest.java
Labels: Pull Request

#91 Introduce rule status
  app/crds/costoptimizationrules.org.jothika.costoperator-v1.yml
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleSpec.java
  app/src/main/java/org/jothika/costoperator/CostOptimizationRuleStatus.java
  app/src/main/java/org/jothika/costoperator/RuleStatus.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/test/java/org/jothika/costoperator/RuleStatusTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
Labels: Pull Request

#92 Github workflow permissions set to read the secrets
  .github/workflows/docker-publish.yml
  .github/workflows/sonarqube.yml
Labels: bug

#93 Workflow added to push docker images to github container registry
  .github/workflows/docker-publish.yml
  app/src/test/java/org/jothika/costoperator/mail/EmailServiceTest.java
Labels: enhancement

#94 Revert github container registry image push
  .github/workflows/docker-publish.yml
Labels: bug

#95 Kubernetes Cost Optimization Operator Helm Charts added
  charts/cost-optimization-operator/.helmignore
  charts/cost-optimization-operator/Chart.yaml
  charts/cost-optimization-operator/templates/_helpers.tpl
  charts/cost-optimization-operator/templates/deployment.yaml
  charts/cost-optimization-operator/templates/emailsecrets.yaml
  charts/cost-optimization-operator/templates/hpa.yaml
  charts/cost-optimization-operator/templates/ingress.yaml
  charts/cost-optimization-operator/templates/service.yaml
  charts/cost-optimization-operator/templates/serviceaccount.yaml
  charts/cost-optimization-operator/values.yaml
Labels: enhancement

#96 Threshold condition added as part of CRD
  app/crds/costoptimizationrules.org.jothika.costoperator-v1.yml
  app/src/main/java/org/jothika/costoperator/Runner.java
  app/src/main/java/org/jothika/costoperator/events/EventGenerator.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/main/java/org/jothika/costoperator/mail/EmailService.java
  app/src/main/java/org/jothika/costoperator/reconciler/CostOptimizationRule.java
  app/src/main/java/org/jothika/costoperator/reconciler/CostOptimizationRuleReconciler.java
  app/src/main/java/org/jothika/costoperator/reconciler/CostOptimizationRuleSpec.java
  app/src/main/java/org/jothika/costoperator/reconciler/CostOptimizationRuleStatus.java
  app/src/main/java/org/jothika/costoperator/reconciler/enums/RuleStatus.java
  app/src/main/java/org/jothika/costoperator/reconciler/enums/ThresholdCondition.java
  app/src/main/resources/templates/pod-alert.html
  app/src/test/java/org/jothika/costoperator/TestMockUtils.java
  app/src/test/java/org/jothika/costoperator/events/EventGeneratorTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/mail/EmailServiceTest.java
  app/src/test/java/org/jothika/costoperator/reconciler/CostOptimizationRuleReconcilerTest.java
  app/src/test/java/org/jothika/costoperator/reconciler/enums/RuleStatusTest.java
  app/src/test/java/org/jothika/costoperator/reconciler/enums/ThresholdConditionTest.java
Labels: enhancement

#99 Helm lint workflow added
  .github/workflows/helm-lint.yml
Labels: enhancement

#101 Rule validator added
  app/crds/costoptimizationrules.org.jothika.costoperator-v1.yml
  app/src/main/java/org/jothika/costoperator/handlers/RuleHandler.java
  app/src/main/java/org/jothika/costoperator/handlers/RuleValidator.java
  app/src/main/java/org/jothika/costoperator/reconciler/enums/RuleStatus.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleValidatorTest.java
  app/src/test/java/org/jothika/costoperator/reconciler/CostOptimizationRuleReconcilerTest.java
Labels: enhancement

#102 Gradle properties updated
  app/build.gradle
  app/src/main/resources/templates/pod-alert.html
  gradle.properties
Labels: enhancement

#103 Jib Configuration Cache Workaround Added
  app/build.gradle
Labels: bug

#104 Release github workflow added
  .github/workflows/release.yml
  app/src/main/resources/banner.txt
Labels: enhancement

#105 Application and chart version upgraded after release
  app/build.gradle
  charts/cost-optimization-operator/Chart.yaml
  charts/cost-optimization-operator/values.yaml
Labels: enhancement

#110 Add initial README, user guide, and install guide
  Install-via-GitHub-Release.md
  README.md
  User-Guide.md
Labels: documentation

#111 Update User-Guide.md
  User-Guide.md
Labels: duplicate

#112 Add first CR file with initial structure
  app/crds/my-first-cr.yaml
Labels: enhancement

#113 Minor document corrections
  User-Guide.md
Labels: Pull Request

#115 Azure VM cleanup added in deployment workflow
  .github/workflows/deploy-to-azure-vm.yml
Labels: Pull Request

#116 Add testing azure vm deployment trigger
  .github/workflows/trigger-testing-azure-deployment.yml
Labels: enhancement

#117 CD machine setup guide added
  Setup-Machine-For-Continous-Delivery.md
Labels: Pull Request

#118 Testing Deployment should trigger on completion of building the image
  .github/workflows/trigger-testing-azure-deployment.yml
Labels: Pull Request

#120 Trivy docker image scan added
  .github/workflows/docker-publish.yml
Labels: enhancement

#121 Spring profile prod added
  .github/workflows/deploy-to-azure-vm.yml
  .github/workflows/docker-publish.yml
  app/src/main/resources/application-prod.properties
  charts/cost-optimization-operator/Chart.yaml
  charts/cost-optimization-operator/templates/deployment.yaml
  charts/cost-optimization-operator/values.yaml
Labels: Pull Request

#122 Sample CR for Demo added
  User-Guide.md
  app/crds/invalid-pod-name-cr.yml
  app/crds/nginx-cpu-greater-than-point-one-cr.yaml
  app/crds/nginx-cpu-less-than-point-one-cr.yaml
Labels: Pull Request

#123 Apache Benchmark tools installation instructions added.
  Installation-Guide.md
Labels: documentation

#124 Email validation added
  app/src/main/java/org/jothika/costoperator/handlers/RuleValidator.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleHandlerTest.java
  app/src/test/java/org/jothika/costoperator/handlers/RuleValidatorTest.java
Labels: Pull Request

#126 Unused gradle dependency versions removed
  app/build.gradle
Labels: Pull Request

#130 Fixed version used for gradle actions
  .github/workflows/gradle.yml
Labels: Pull Request

#134 Version upgrade to 0.3.0 after release
  Developer-Guide.md
  Install-via-GitHub-Release.md
  Installation-Guide.md
  README.md
  User-Guide.md
  app/build.gradle
Labels: Pull Request
